RA-317 Fixed Info Button on Meeting Mediator
rifflearning/jitsi-meet pull request #134
Opened 2021-12-10 16:08 UTC by olivermillard

## Description
Fixed the meeting mediator's info button which was closing the meeting mediator on click because of overlap with the close button. This issue was resolved by switching `padding` to `margin` in the `meeting-mediator-close`'s styling.  

## Motivation and context
This was a bug; jira ticket was [RA-317](https://riffanalytics.atlassian.net/browse/RA-317)

## How has this been tested?
This has been tested by deploying jitsi to sandbox1.

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

2021-12-10 16:45 UTC, jordanreedie approved these changes

2021-12-10 16:50 UTC, jordanreedie requested changes

2021-12-10 16:50 UTC, jordanreedie commented on css/riff-styles.scss
> +        margin: 5px;
```suggestion
```

2022-01-21 20:42 UTC, mlippert approved these changes

2022-01-21 20:59 UTC, merged