disable sibilant and other meeting events
rifflearning/jitsi-meet pull request #146
Opened 2022-07-08 08:48 UTC by Balu-Varanasi

Still need to remove the related code, but this disables it at least

## Description

## Motivation and context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- ✅ Maintenance (change which doesn't modify functionality, but provides dependency updates or tooling improvements)
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Refactor (non-breaking change which doesn't change functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

2022-07-08 16:59 UTC, mlippert commented
force pushed to rebase to HEAD of `riff/mods_7439` (also split out package-lock.json changes to its own commit)

2022-07-08 17:00 UTC, mlippert commented
Please update the description with relevant details.

2022-07-12 10:23 UTC, Balu-Varanasi commented
@mlippert: Thanks for rebasing. I made changes to the PR title and description as per our Riff Guidelines. Please review again.

2022-07-13 10:28 UTC, Balu-Varanasi commented
> it looks like there is still some leftover unused code around the feathers app (riffClient.js), storing the feathers app access token, and storing meeting IDs

Thanks, @jordanreedie. I am making the necessary changes now

2022-07-13 17:16 UTC, mlippert requested changes

2022-07-13 17:16 UTC, mlippert commented on package.json
>      "@rifflearning/riff-metrics": "^4.1.0-dev.1",
I believe that the riff-metrics package is also only here because of sending the utterances to the riffdata server. So it (and where it might still be used) should be removed.

2022-07-13 17:16 UTC, kinger68 commented
We should remove the riffConfig object (riff_config.js). That file is no longer needed.

2022-07-14 14:36 UTC, jordanreedie requested changes
grepping for removed config file:

```
jitsi-meet on  feature/remove-sibilant [$?] is 📦 v2.4.0-jitsi.7439 via ⬢ v16.13.1
➜ grep 'riff_config' -r . --exclude-dir={resources,node_modules,.git} --exclude=tags
./index.html:            "riff_config.js",
./index.html:    <script><!--#include virtual="/riff_config.js" --></script>
./static/prejoin.html:    <script><!--#include virtual="/riff_config.js" --></script>```

2022-07-14 20:01 UTC, mlippert approved these changes
:+1:

2022-07-14 20:12 UTC, mlippert commented
@Balu-Varanasi I updated the description here a little bit. What you had as a description before was more about the motivation, so I moved that to the _Motivation and context_ section (and then edited it a little bit), and I added more of a description of what was being done in the description section.

See if my changes make sense to you.

2022-07-15 11:53 UTC, Balu-Varanasi commented
Making sense @mlippert. Thank you! I made those changes @jordanreedie. Thank you very much!!

2022-07-15 12:07 UTC, jordanreedie approved these changes

2022-07-15 18:10 UTC, mlippert approved these changes

2022-07-15 18:16 UTC, merged