Add support for multiplexed email field (RA-768)
rifflearning/jitsi-meet pull request #147
Opened 2022-07-12 14:15 UTC by jordanreedie

## Description
Adds the ability to pass in a stringified JSON object in place of the email field. If a regular email is passed instead of a stringified object, the gravatars should still work. 

## Motivation and context
Required (for now) to get additional information to Jigasi without significant further changes.
See: https://esme-learning.atlassian.net/browse/RA-768

## How has this been tested?
Tested locally

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

2022-07-12 17:48 UTC, kinger68 requested changes

2022-07-12 18:07 UTC, jordanreedie commented on react/features/riff-integration/functions.js
> + * @param {string} email - The participant's email to parse
Ah it does not return the json object, it extracts the email from the json object and returns that

2022-07-12 18:15 UTC, jordanreedie commented on react/features/riff-integration/functions.js
> + * @returns {string} - The parsed email, or the input string on failure
The only case in which we can return `null` is if the function is called with `null` as its argument, which is explicitly outside the range of acceptable inputs defined in the jsdoc. If there is no email field in the JSON string, we return the input as we received it (ie a string), and if there is an email field but it is populated with `""`, then we return `""` which is a valid string.

2022-07-12 18:18 UTC, jordanreedie commented on react/features/riff-integration/functions.js
> + * @param {string} email - The participant's email to parse
Oh sorry i read this comment as if it was on the line below it (ie about what it was returning), sorry, I see what you're saying, though I'll note that it's a stringified json object to avoid confusion there

2022-07-13 14:21 UTC, Balu-Varanasi approved these changes
LGTM overall.

2022-07-13 15:52 UTC, jordanreedie commented
squashed and force pushed after PR approval

2022-07-13 17:34 UTC, mlippert approved these changes

2022-07-13 17:37 UTC, merged